/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read closed-initialization status */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first administrator */
        post: operations["initializeAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an opaque database session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current session user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List consistent system backups */
        get: operations["listBackups"];
        put?: never;
        /** Create a consistent system backup */
        post: operations["createBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        /** Download a system backup */
        get: operations["downloadBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically restore a system backup */
        post: operations["restoreBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current user's viewing calendar */
        get: operations["getCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List private collections */
        get: operations["listCollections"];
        put?: never;
        /** Create a private collection */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collectionID}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionID: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Replace and order items in a private collection */
        put: operations["replaceCollectionItems"];
        /** Add media to a private collection */
        post: operations["addCollectionItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export current-user viewing data */
        get: operations["exportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import validated current-user viewing data */
        post: operations["importData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current-user media server account metadata */
        get: operations["listIntegrationAccounts"];
        put?: never;
        /** Encrypt and create a current-user media server account */
        post: operations["createIntegrationAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/accounts/{accountID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect an owned media server account */
        delete: operations["disconnectIntegrationAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's media library */
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the local media catalog */
        get: operations["searchLocalMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{mediaID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        /** Read the current user's media record */
        get: operations["getRecord"];
        /** Update a versioned current-user media record */
        put: operations["updateRecord"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{mediaID}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        /** Read the current user's private tags for a media record */
        get: operations["getRecordTags"];
        /** Replace private tags for a media record */
        put: operations["setRecordTags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{mediaID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        /** List immutable watch events for a media record */
        get: operations["listWatchEvents"];
        put?: never;
        /** Create an immutable rewatch event */
        post: operations["createWatchEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{mediaID}/events/{eventID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
                eventID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an owned watch event */
        delete: operations["deleteWatchEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{mediaID}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        /** Read episode progress for a series */
        get: operations["getEpisodeProgress"];
        put?: never;
        /** Apply an idempotent episode progress action */
        post: operations["updateEpisodeProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read private accessible viewing statistics */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read current-user integration sync status */
        get: operations["getSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current-user sync candidates */
        get: operations["listSyncCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/candidates/{candidateID}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a proposed sync match */
        post: operations["confirmSyncCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/candidates/{candidateID}/rematch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rematch a sync candidate to another local item */
        post: operations["rematchSyncCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/candidates/{candidateID}/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ignore a sync candidate */
        post: operations["ignoreSyncCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/candidates/{candidateID}/custom": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create custom media for an unmatched sync candidate */
        post: operations["createCustomSyncCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List minimal shared household events */
        get: operations["listSharedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List household members */
        get: operations["listHouseholdMembers"];
        put?: never;
        /** Create a household member */
        post: operations["createHouseholdMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active co-viewing participants */
        get: operations["listHouseholdParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/members/{memberID}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberID: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a household member password */
        post: operations["resetHouseholdMemberPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/members/{memberID}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberID: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a household member and sessions */
        post: operations["deactivateHouseholdMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/records/{ownerID}/{mediaID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerID: string;
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        /** Read explicitly shared household record fields */
        get: operations["getVisibleHouseholdRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household/records/{mediaID}/sharing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        /** Read the current user's household sharing settings */
        get: operations["getHouseholdSharing"];
        /** Update explicit household sharing flags */
        put: operations["updateHouseholdSharing"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tmdb/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read server-side TMDB configuration status */
        get: operations["getTMDBStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tmdb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search TMDB through the server adapter */
        get: operations["searchTMDB"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tmdb/movie/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
            };
            cookie?: never;
        };
        /** Read normalized TMDB movie details */
        get: operations["getTMDBMovie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tmdb/tv/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
            };
            cookie?: never;
        };
        /** Read normalized TMDB series details */
        get: operations["getTMDBTV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tmdb/tv/{id}/season/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
                season: number;
            };
            cookie?: never;
        };
        /** Read a normalized TMDB season */
        get: operations["getTMDBSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tmdb/tv/{id}/season/{season}/episode/{episode}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
                season: number;
                episode: number;
            };
            cookie?: never;
        };
        /** Read a normalized TMDB episode */
        get: operations["getTMDBEpisode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tmdb/{mediaType}/{id}/credits": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaType: components["parameters"]["MediaType"];
                id: components["parameters"]["TMDBID"];
            };
            cookie?: never;
        };
        /** Read normalized ordered TMDB cast */
        get: operations["getTMDBCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Read a local media item */
        get: operations["getMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/tmdb/{mediaType}/{externalID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaType: components["parameters"]["MediaType"];
                externalID: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or refresh local media from TMDB */
        post: operations["createMediaFromTMDB"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a custom local media item */
        post: operations["createCustomMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}/tmdb/{mediaType}/{externalID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                mediaType: components["parameters"]["MediaType"];
                externalID: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link existing custom media to TMDB */
        post: operations["linkMediaToTMDB"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EmptyObject: Record<string, never>;
        FileUpload: {
            /** Format: binary */
            file: string;
        };
        SetupStatus: {
            initialized: boolean;
            storageReady: boolean;
            tmdbConfigured: boolean;
        };
        CredentialsRequest: {
            username: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "admin" | "member";
        };
        LoginResponse: {
            user: components["schemas"]["User"];
            csrfToken: string;
        };
        BackupManifest: {
            formatVersion: number;
            schemaVersion: number;
            /** Format: date-time */
            createdAt: string;
            databaseSha256: string;
            databaseBytes: number;
            requiresEncryptionKey: boolean;
        };
        BackupArtifact: {
            filename: string;
            bytes: number;
            manifest: components["schemas"]["BackupManifest"];
        };
        BackupList: components["schemas"]["BackupArtifact"][];
        RestoreResult: {
            preRestoreBackup: string;
            warnings: string[];
        };
        /** @enum {string} */
        RecordStatus: "none" | "wishlist" | "watching" | "completed" | "dropped";
        /** @enum {string} */
        RecordSource: "manual" | "confirmed_import" | "confirmed_sync" | "external_default";
        /** @enum {string} */
        MediaType: "movie" | "tv";
        CalendarEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            mediaId: string;
            mediaType: components["schemas"]["MediaType"];
            title: string;
            /** Format: uuid */
            episodeId: string | null;
            seasonNumber: number | null;
            episodeNumber: number | null;
            absoluteNumber: number | null;
            /** Format: date-time */
            watchedAt: string;
            /** Format: date */
            localDate: string;
            viewingMethod: string | null;
            participants: string[];
            status: components["schemas"]["RecordStatus"];
        };
        CalendarResponse: {
            year: number;
            month: number;
            timezone: string;
            events: components["schemas"]["CalendarEvent"][];
        };
        Collection: {
            /** Format: uuid */
            id: string;
            name: string;
            items: string[];
        };
        CollectionList: components["schemas"]["Collection"][];
        CreateCollectionRequest: {
            name: string;
        };
        AddCollectionItemRequest: {
            /** Format: uuid */
            mediaId: string;
        };
        ReplaceCollectionItemsRequest: {
            mediaIds: string[];
        };
        IntegrationAccount: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            provider: "jellyfin" | "emby" | "plex";
            name: string;
            credentialFingerprint: string;
            enabled: boolean;
            locked: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        IntegrationAccountList: components["schemas"]["IntegrationAccount"][];
        CreateIntegrationAccountRequest: {
            /** @enum {string} */
            provider: "jellyfin" | "emby" | "plex";
            name: string;
            /** Format: uri */
            baseUrl: string;
            token: string;
            userId?: string;
            accountId?: number;
            timezone?: string;
        };
        CatalogItem: {
            /** Format: uuid */
            id: string;
            tmdbId: number | null;
            /** @enum {string} */
            source: "local";
            mediaType: components["schemas"]["MediaType"];
            title: string;
            originalTitle: string;
            year: string;
            posterPath: string | null;
            status: components["schemas"]["RecordStatus"];
        };
        CursorPage: {
            items: components["schemas"]["CatalogItem"][];
            nextCursor: string | null;
        };
        CatalogSearchResponse: {
            items: components["schemas"]["CatalogItem"][];
        };
        RecordState: {
            /** Format: uuid */
            mediaId: string;
            status: components["schemas"]["RecordStatus"];
            rating: number | null;
            note: string | null;
            /** Format: date-time */
            watchedAt: string | null;
            viewingMethod: string | null;
            version: number;
        };
        UpdateRecordRequest: {
            status: components["schemas"]["RecordStatus"];
            rating?: number | null;
            note?: string | null;
            /** Format: date-time */
            watchedAt?: string;
            viewingMethod?: string | null;
            participantIds?: string[];
        };
        TagsRequest: {
            tags: string[];
        };
        WatchEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            mediaId: string;
            /** Format: uuid */
            episodeId?: string;
            /** Format: date-time */
            watchedAt: string;
            viewingMethod?: string;
            source: components["schemas"]["RecordSource"];
            externalEventId?: string;
            completion: number;
            note?: string;
        };
        WatchEventList: components["schemas"]["WatchEvent"][];
        CreateWatchEventRequest: {
            /** Format: date-time */
            watchedAt: string;
            viewingMethod?: string;
            note?: string;
        };
        EpisodeProgressItem: {
            /** Format: uuid */
            id: string;
            sourceId: string;
            /** Format: uuid */
            seasonId: string;
            seasonNumber: number;
            episodeNumber: number;
            absoluteNumber: number;
            name: string;
            watched: boolean;
            /** Format: date-time */
            watchedAt: string | null;
        };
        EpisodeProgress: {
            /** Format: uuid */
            mediaId: string;
            status: components["schemas"]["RecordStatus"];
            version: number;
            watchedEpisodes: number;
            totalEpisodes: number;
            lastWatched: components["schemas"]["EpisodeProgressItem"] | null;
            nextEpisode: components["schemas"]["EpisodeProgressItem"] | null;
            episodes: components["schemas"]["EpisodeProgressItem"][];
        };
        EpisodeReference: {
            sourceId: string;
            seasonNumber: number;
            episodeNumber: number;
            absoluteNumber: number;
        };
        UpdateEpisodeProgressRequest: {
            /** @enum {string} */
            action: "single" | "range" | "season" | "next" | "undo";
            /** Format: uuid */
            episodeId?: string;
            /** Format: uuid */
            throughEpisodeId?: string;
            /** Format: uuid */
            seasonId?: string;
            episodeRefs?: components["schemas"]["EpisodeReference"][];
            totalEpisodes?: number;
            /** Format: date-time */
            watchedAt?: string;
            expectedVersion: number;
        };
        StatsPoint: {
            label: string;
            value: number;
        };
        StatsSummary: {
            totalWatches: number;
            uniqueMedia: number;
            totalMinutes: number;
            repeatWatches: number;
            monthly: components["schemas"]["StatsPoint"][];
            yearly: components["schemas"]["StatsPoint"][];
            genres: components["schemas"]["StatsPoint"][];
            ratings: components["schemas"]["StatsPoint"][];
            tags: components["schemas"]["StatsPoint"][];
            viewingMethods: components["schemas"]["StatsPoint"][];
        };
        SyncAccountStatus: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            provider: "jellyfin" | "emby" | "plex";
            name: string;
            enabled: boolean;
            pendingCandidates: number;
            /** @enum {string} */
            lastRunStatus?: "running" | "succeeded" | "failed";
            /** Format: date-time */
            lastRunAt?: string;
        };
        SyncStatus: {
            accounts: components["schemas"]["SyncAccountStatus"][];
            pendingTotal: number;
        };
        /** @enum {string} */
        SyncCandidateStatus: "exact" | "possible" | "unmatched" | "conflict" | "confirmed" | "ignored";
        SyncEvidence: {
            code: string;
            text: string;
        };
        SyncMatchOption: {
            /** Format: uuid */
            mediaId: string;
            /** Format: uuid */
            episodeId?: string;
            mediaType: components["schemas"]["MediaType"];
            title: string;
            originalTitle?: string;
            year?: string;
        };
        SyncCandidateEvent: {
            /** Format: date-time */
            playedAt: string;
            durationSeconds: number;
            positionSeconds: number;
            providerItemId: string;
            /** @enum {string} */
            mediaType: "movie" | "episode";
            title: string;
            originalTitle?: string;
            year?: number;
            seasonNumber?: number;
            episodeNumber?: number;
        };
        SyncCandidate: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            externalEventId: string;
            status: components["schemas"]["SyncCandidateStatus"];
            /** Format: uuid */
            mediaId?: string;
            /** Format: uuid */
            episodeId?: string;
            event: components["schemas"]["SyncCandidateEvent"];
            evidence: components["schemas"]["SyncEvidence"][];
            options: components["schemas"]["SyncMatchOption"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SyncCandidateList: components["schemas"]["SyncCandidate"][];
        RematchCandidateRequest: {
            /** Format: uuid */
            mediaId: string;
            /** Format: uuid */
            episodeId?: string;
        };
        CustomMediaRequest: {
            title: string;
            mediaType: components["schemas"]["MediaType"];
            overview?: string;
            year?: string;
        };
        Member: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "admin" | "member";
            active: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        MemberList: components["schemas"]["Member"][];
        CreateMemberRequest: {
            username: string;
            password: string;
        };
        ResetPasswordRequest: {
            password: string;
        };
        SharingRequest: {
            shareRating: boolean;
            shareReview: boolean;
            sharedReview: string;
            expectedVersion: number;
        };
        SharingResponse: {
            /** Format: uuid */
            mediaId: string;
            shareRating: boolean;
            shareReview: boolean;
            sharedReview: string | null;
            version: number;
        };
        VisibleRecord: {
            /** Format: uuid */
            ownerId: string;
            /** Format: uuid */
            mediaId: string;
            rating: number | null;
            privateNote: string | null;
            sharedReview: string | null;
        };
        SharedEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            mediaId: string;
            title: string;
            /** Format: date-time */
            watchedAt: string;
            participants: string[];
        };
        SharedEventList: components["schemas"]["SharedEvent"][];
        TMDBStatus: {
            configured: boolean;
        };
        TMDBSearchResult: {
            id: number;
            mediaType: components["schemas"]["MediaType"];
            title: string;
            originalTitle: string;
            year: string;
            posterPath: string;
            overview: string;
        };
        TMDBSearchResponse: {
            page: number;
            results: components["schemas"]["TMDBSearchResult"][];
            totalPages: number;
            totalResults: number;
        };
        TMDBMovie: {
            id: number;
            title: string;
            originalTitle: string;
            releaseDate: string;
            posterPath: string;
            backdropPath: string;
            overview: string;
            runtime: number;
            genres: string[];
        };
        TMDBSeasonSummary: {
            id: number;
            name: string;
            overview: string;
            posterPath: string;
            airDate: string;
            seasonNumber: number;
            episodeCount: number;
        };
        TMDBTV: {
            id: number;
            name: string;
            originalName: string;
            firstAirDate: string;
            posterPath: string;
            backdropPath: string;
            overview: string;
            numberOfSeasons: number;
            numberOfEpisodes: number;
            episodeRuntime: number[];
            genres: string[];
            seasons: components["schemas"]["TMDBSeasonSummary"][];
        };
        TMDBEpisode: {
            id: number;
            name: string;
            overview: string;
            airDate: string;
            seasonNumber: number;
            episodeNumber: number;
            runtime: number;
            stillPath: string;
        };
        TMDBSeason: {
            id: number;
            name: string;
            overview: string;
            posterPath: string;
            airDate: string;
            seasonNumber: number;
            episodes: components["schemas"]["TMDBEpisode"][];
        };
        TMDBCastMember: {
            id: number;
            name: string;
            character: string;
            profilePath: string;
            order: number;
        };
        TMDBCredits: {
            cast: components["schemas"]["TMDBCastMember"][];
        };
        MediaItem: {
            /** Format: uuid */
            id: string;
            tmdbId: number | null;
            mediaType: components["schemas"]["MediaType"];
            title: string;
            overview: string;
            externalTitle: string;
            externalOverview: string;
            originalTitle: string;
            releaseDate: string;
            posterPath: string;
            backdropPath: string;
            runtimeMinutes: number;
            genres: string[];
        };
        ImportFailure: {
            recordId: string;
            code: string;
        };
        ImportReport: {
            importedRecords: number;
            importedCollections: number;
            failures: components["schemas"]["ImportFailure"][];
        };
        ExportExternalID: {
            source: string;
            sourceId: string;
            mediaType: components["schemas"]["MediaType"];
        };
        ExportGenre: {
            source: string;
            sourceId: string;
            name: string;
        };
        ExportEpisode: {
            /** Format: uuid */
            id: string;
            sourceId?: string;
            episodeNumber: number;
            name: string;
            overview: string;
            stillPath: string;
            airDate: string;
            runtime?: number;
        };
        ExportSeason: {
            /** Format: uuid */
            id: string;
            sourceId?: string;
            seasonNumber: number;
            name: string;
            overview: string;
            posterPath: string;
            airDate: string;
            episodes: components["schemas"]["ExportEpisode"][];
        };
        ExportMedia: {
            /** Format: uuid */
            id: string;
            mediaType: components["schemas"]["MediaType"];
            externalTitle: string;
            originalTitle: string;
            releaseDate: string;
            externalOverview: string;
            posterPath: string;
            backdropPath: string;
            customTitle?: string;
            customOverview?: string;
            customYear?: string;
            runtimeMinutes?: number;
            externalIds: components["schemas"]["ExportExternalID"][];
            genres: components["schemas"]["ExportGenre"][];
            seasons: components["schemas"]["ExportSeason"][];
        };
        ExportState: {
            status: components["schemas"]["RecordStatus"];
            rating?: number;
            note?: string;
            version: number;
            statusSource: components["schemas"]["RecordSource"];
            ratingSource: components["schemas"]["RecordSource"];
            noteSource: components["schemas"]["RecordSource"];
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            shareRating: boolean;
            shareReview: boolean;
            sharedReview?: string;
        };
        ExportEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            episodeId?: string;
            /** Format: date-time */
            watchedAt: string;
            viewingMethod?: string;
            source: components["schemas"]["RecordSource"];
            externalEventId?: string;
            completion: number;
            note?: string;
        };
        ExportProgress: {
            /** Format: uuid */
            episodeId: string;
            /** Format: date-time */
            watchedAt: string;
            source: components["schemas"]["RecordSource"];
            /** Format: uuid */
            watchEventId: string;
        };
        ExportRecord: {
            media: components["schemas"]["ExportMedia"];
            state?: components["schemas"]["ExportState"];
            tags: string[];
            events: components["schemas"]["ExportEvent"][];
            progress: components["schemas"]["ExportProgress"][];
        };
        ExportCollection: {
            /** Format: uuid */
            id: string;
            name: string;
            mediaIds: string[];
        };
        ExportDocument: {
            /** @constant */
            version: 1;
            records: components["schemas"]["ExportRecord"][];
            collections: components["schemas"]["ExportCollection"][];
        };
        ProblemDetails: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            code: string;
            requestId: string;
        };
    };
    responses: {
        /** @description RFC 9457 Problem Details response. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        CSRFToken: string;
        IfMatch: string;
        MediaID: string;
        CandidateID: string;
        MemberID: string;
        TMDBID: number;
        MediaType: components["schemas"]["MediaType"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    initializeAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Administrator created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listBackups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup artifacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createBackup: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
        responses: {
            /** @description Backup created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupArtifact"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    downloadBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup archive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.video-record.backup": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreBackup: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["FileUpload"];
            };
        };
        responses: {
            /** @description Restore committed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCalendar: {
        parameters: {
            query: {
                month: string;
                timezone: string;
                filter?: "all" | "completed" | "in_progress";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar month. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCollections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private collections. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionRequest"];
            };
        };
        responses: {
            /** @description Collection created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    replaceCollectionItems: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                collectionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceCollectionItemsRequest"];
            };
        };
        responses: {
            /** @description Collection items replaced in the supplied order. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    addCollectionItem: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                collectionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCollectionItemRequest"];
            };
        };
        responses: {
            /** @description Collection item added. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    exportData: {
        parameters: {
            query: {
                format: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportDocument"];
                    "text/csv; charset=utf-8": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    importData: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["FileUpload"];
            };
        };
        responses: {
            /** @description Import report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReport"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listIntegrationAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encrypted integration account metadata without credentials or base URLs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationAccountList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createIntegrationAccount: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntegrationAccountRequest"];
            };
        };
        responses: {
            /** @description Integration account created and sync jobs provisioned. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationAccount"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    disconnectIntegrationAccount: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                accountID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration account disconnected. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getLibrary: {
        parameters: {
            query?: {
                status?: components["schemas"]["RecordStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-shaped library page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    searchLocalMedia: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSearchResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current media record. */
            200: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordState"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateRecord: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecordRequest"];
            };
        };
        responses: {
            /** @description Updated media record. */
            200: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordState"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRecordTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current private tags. */
            200: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsRequest"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setRecordTags: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsRequest"];
            };
        };
        responses: {
            /** @description Tags replaced. */
            204: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listWatchEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watch events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchEventList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createWatchEvent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchEventRequest"];
            };
        };
        responses: {
            /** @description Watch event created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchEvent"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteWatchEvent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                mediaID: components["parameters"]["MediaID"];
                eventID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watch event deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getEpisodeProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episode progress. */
            200: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeProgress"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateEpisodeProgress: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEpisodeProgressRequest"];
            };
        };
        responses: {
            /** @description Updated episode progress. */
            200: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeProgress"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getStats: {
        parameters: {
            query?: {
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Viewing statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummary"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listSyncCandidates: {
        parameters: {
            query?: {
                status?: components["schemas"]["SyncCandidateStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync candidates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCandidateList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    confirmSyncCandidate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
        responses: {
            /** @description Confirmed candidate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCandidate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    rematchSyncCandidate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RematchCandidateRequest"];
            };
        };
        responses: {
            /** @description Rematched candidate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCandidate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    ignoreSyncCandidate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
        responses: {
            /** @description Ignored candidate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCandidate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCustomSyncCandidate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                candidateID: components["parameters"]["CandidateID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomMediaRequest"];
            };
        };
        responses: {
            /** @description Confirmed custom candidate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncCandidate"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listSharedEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shared events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedEventList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listHouseholdMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Household members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createHouseholdMember: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberRequest"];
            };
        };
        responses: {
            /** @description Household member created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listHouseholdParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active participants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    resetHouseholdMemberPassword: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                memberID: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset and sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    deactivateHouseholdMember: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                memberID: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
        responses: {
            /** @description Member deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getVisibleHouseholdRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ownerID: string;
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Explicitly shared record fields. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisibleRecord"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getHouseholdSharing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current sharing settings. */
            200: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharingResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateHouseholdSharing: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                mediaID: components["parameters"]["MediaID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SharingRequest"];
            };
        };
        responses: {
            /** @description Updated sharing settings. */
            200: {
                headers: {
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharingResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTMDBStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TMDB configuration status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TMDBStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    searchTMDB: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized TMDB search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TMDBSearchResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTMDBMovie: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TMDB movie details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TMDBMovie"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTMDBTV: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TMDB series details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TMDBTV"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTMDBSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
                season: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TMDB season details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TMDBSeason"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTMDBEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TMDBID"];
                season: number;
                episode: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TMDB episode details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TMDBEpisode"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTMDBCredits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaType: components["parameters"]["MediaType"];
                id: components["parameters"]["TMDBID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered TMDB cast. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TMDBCredits"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local media item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createMediaFromTMDB: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                mediaType: components["parameters"]["MediaType"];
                externalID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local media item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCustomMedia: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomMediaRequest"];
            };
        };
        responses: {
            /** @description Custom media item created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    linkMediaToTMDB: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path: {
                id: string;
                mediaType: components["parameters"]["MediaType"];
                externalID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linked media item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
